import { MaterialCommunityIcons } from "@expo/vector-icons";

export type AchievementCategory =
  | "workout"
  | "nutrition"
  | "consistency"
  | "social"
  | "weight"
  | "water"
  | "account";

export type AchievementRarity =
  | "common"
  | "uncommon"
  | "rare"
  | "epic"
  | "legendary";

export interface Achievement {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  hidden?: boolean; // Se a conquista é secreta
  threshold: number; // Valor necessário para desbloquear
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  rarity: AchievementRarity;
  badgeColor: string;
  fitPoints: number;
  fitPointsIcon: keyof typeof MaterialCommunityIcons.glyphMap;
  trackedValue: string; // Nome da propriedade que será rastreada (ex: "workoutCount", "loginDays")
}

// Cores para as medalhas baseadas na raridade
export const RARITY_COLORS = {
  common: "#B0B0B0", // Cinza
  uncommon: "#64B964", // Verde
  rare: "#5387DF", // Azul
  epic: "#A759D8", // Roxo
  legendary: "#FBA61C", // Dourado
};

// Banco de dados de conquistas
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "account_creation",
    name: "Começo da Jornada",
    description: "Bem-vindo ao PumpGym! Sua jornada fitness começou.",
    category: "account",
    threshold: 1,
    icon: "account-check",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 25,
    fitPointsIcon: "account-check",
    trackedValue: "accountCreated",
  },
  {
    id: "workout_completion_1",
    name: "Primeiros Passos",
    description: "Complete seu primeiro treino",
    category: "workout",
    threshold: 1,
    icon: "weight-lifter",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "weight-lifter",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_2",
    name: "Dedicado",
    description: "Complete 5 treinos",
    category: "workout",
    threshold: 5,
    icon: "dumbbell",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "dumbbell",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_3",
    name: "Consistente",
    description: "Complete 25 treinos",
    category: "workout",
    threshold: 25,
    icon: "arm-flex-outline",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "arm-flex-outline",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_4",
    name: "Atleta",
    description: "Complete 100 treinos",
    category: "workout",
    threshold: 100,
    icon: "trophy-outline",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 300,
    fitPointsIcon: "trophy-outline",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_5",
    name: "Lendário",
    description: "Complete 365 treinos",
    category: "workout",
    threshold: 365,
    icon: "trophy",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 600,
    fitPointsIcon: "trophy",
    trackedValue: "workoutCount",
  },
  {
    id: "streak_days_1",
    name: "Faísca",
    description: "3 dias consecutivos de treino",
    category: "consistency",
    threshold: 3,
    icon: "fire",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 75,
    fitPointsIcon: "fire",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_2",
    name: "Chama",
    description: "7 dias consecutivos de treino",
    category: "consistency",
    threshold: 7,
    icon: "fire",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "fire",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_3",
    name: "Incêndio",
    description: "14 dias consecutivos de treino",
    category: "consistency",
    threshold: 14,
    icon: "fireplace",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "fireplace",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_4",
    name: "Inferno",
    description: "30 dias consecutivos de treino",
    category: "consistency",
    threshold: 30,
    icon: "fire-circle",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 500,
    fitPointsIcon: "fire-circle",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_5",
    name: "Fênix",
    description: "90 dias consecutivos de treino",
    category: "consistency",
    threshold: 90,
    icon: "meteor",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "meteor",
    trackedValue: "streakDays",
  },
  {
    id: "nutrition_goals_1",
    name: "Iniciante Nutricional",
    description: "Atinja suas metas de macros 1 dia",
    category: "nutrition",
    threshold: 1,
    icon: "food-apple",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "food-apple",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_2",
    name: "Consciente",
    description: "Atinja suas metas de macros 7 dias",
    category: "nutrition",
    threshold: 7,
    icon: "food-apple-outline",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "food-apple-outline",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_3",
    name: "Disciplinado",
    description: "Atinja suas metas de macros 30 dias",
    category: "nutrition",
    threshold: 30,
    icon: "fruit-watermelon",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "fruit-watermelon",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_4",
    name: "Nutricionista Amador",
    description: "Atinja suas metas de macros 90 dias",
    category: "nutrition",
    threshold: 90,
    icon: "food-variant",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 500,
    fitPointsIcon: "food-variant",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_5",
    name: "Guru Nutricional",
    description: "Atinja suas metas de macros 180 dias",
    category: "nutrition",
    threshold: 180,
    icon: "food-fork-drink",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 750,
    fitPointsIcon: "food-fork-drink",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "water_intake_1",
    name: "Gota d'água",
    description: "Atinja sua meta de água 1 dia",
    category: "water",
    threshold: 1,
    icon: "water-outline",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 25,
    fitPointsIcon: "water-outline",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_2",
    name: "Fonte",
    description: "Atinja sua meta de água 7 dias",
    category: "water",
    threshold: 7,
    icon: "water",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "water",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_3",
    name: "Rio",
    description: "Atinja sua meta de água 30 dias",
    category: "water",
    threshold: 30,
    icon: "cup-water",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "cup-water",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_4",
    name: "Cascata",
    description: "Atinja sua meta de água 90 dias",
    category: "water",
    threshold: 90,
    icon: "waves",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 375,
    fitPointsIcon: "waves",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_5",
    name: "Oceano",
    description: "Atinja sua meta de água 180 dias",
    category: "water",
    threshold: 180,
    icon: "diving-helmet",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 600,
    fitPointsIcon: "diving-helmet",
    trackedValue: "waterGoalDays",
  },
  {
    id: "weight_goals_1",
    name: "Primeiros Quilos",
    description: "Alcance 10% do seu objetivo de peso",
    category: "weight",
    threshold: 10,
    icon: "scale-bathroom",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "scale-bathroom",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_2",
    name: "No Caminho",
    description: "Alcance 25% do seu objetivo de peso",
    category: "weight",
    threshold: 25,
    icon: "progress-check",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 150,
    fitPointsIcon: "progress-check",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_3",
    name: "Meio Caminho",
    description: "Alcance 50% do seu objetivo de peso",
    category: "weight",
    threshold: 50,
    icon: "progress-clock",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "progress-clock",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_4",
    name: "Quase Lá",
    description: "Alcance 75% do seu objetivo de peso",
    category: "weight",
    threshold: 75,
    icon: "progress-star",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 375,
    fitPointsIcon: "progress-star",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_5",
    name: "Metamorfose Completa",
    description: "Alcance 100% do seu objetivo de peso",
    category: "weight",
    threshold: 100,
    icon: "butterfly",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 750,
    fitPointsIcon: "butterfly",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "exercise_variety_1",
    name: "Curioso",
    description: "Experimente 5 exercícios diferentes",
    category: "workout",
    threshold: 5,
    icon: "dumbbell",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "dumbbell",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_2",
    name: "Aventureiro",
    description: "Experimente 15 exercícios diferentes",
    category: "workout",
    threshold: 15,
    icon: "yoga",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "yoga",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_3",
    name: "Versátil",
    description: "Experimente 30 exercícios diferentes",
    category: "workout",
    threshold: 30,
    icon: "run",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 175,
    fitPointsIcon: "run",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_4",
    name: "Mestre da Variedade",
    description: "Experimente 50 exercícios diferentes",
    category: "workout",
    threshold: 50,
    icon: "karate",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 300,
    fitPointsIcon: "karate",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_5",
    name: "Enciclopédia Viva",
    description: "Experimente 100 exercícios diferentes",
    category: "workout",
    threshold: 100,
    icon: "book-open-variant",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 500,
    fitPointsIcon: "book-open-variant",
    trackedValue: "uniqueExercises",
  },
  {
    id: "app_usage_1",
    name: "Novato",
    description: "Use o app por 7 dias",
    category: "consistency",
    threshold: 7,
    icon: "cellphone-check",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "cellphone-check",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_2",
    name: "Regular",
    description: "Use o app por 30 dias",
    category: "consistency",
    threshold: 30,
    icon: "cellphone-arrow-down",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "cellphone-arrow-down",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_3",
    name: "Dedicado",
    description: "Use o app por 90 dias",
    category: "consistency",
    threshold: 90,
    icon: "cellphone-link",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "cellphone-link",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_4",
    name: "Leal",
    description: "Use o app por 180 dias",
    category: "consistency",
    threshold: 180,
    icon: "cellphone-message",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 500,
    fitPointsIcon: "cellphone-message",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_5",
    name: "Vitalício",
    description: "Use o app por 365 dias",
    category: "consistency",
    threshold: 365,
    icon: "cellphone-nfc",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "cellphone-nfc",
    trackedValue: "appUsageDays",
  },
  {
    id: "meal_tracking_1",
    name: "Iniciante Culinário",
    description: "Registre 7 dias de refeições",
    category: "nutrition",
    threshold: 7,
    icon: "silverware-fork-knife",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "silverware-fork-knife",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_2",
    name: "Gourmet Amador",
    description: "Registre 30 dias de refeições",
    category: "nutrition",
    threshold: 30,
    icon: "silverware",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "silverware",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_3",
    name: "Chef de Nutrição",
    description: "Registre 90 dias de refeições",
    category: "nutrition",
    threshold: 90,
    icon: "food-steak",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "food-steak",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_4",
    name: "Mestre Culinário",
    description: "Registre 180 dias de refeições",
    category: "nutrition",
    threshold: 180,
    icon: "food-turkey",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 500,
    fitPointsIcon: "food-turkey",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_5",
    name: "Lenda da Gastronomia",
    description: "Registre 365 dias de refeições",
    category: "nutrition",
    threshold: 365,
    icon: "chef-hat",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 750,
    fitPointsIcon: "chef-hat",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "weight_tracking_1",
    name: "Observador",
    description: "Registre seu peso 5 vezes",
    category: "weight",
    threshold: 5,
    icon: "scale",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "scale",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_2",
    name: "Atento",
    description: "Registre seu peso 15 vezes",
    category: "weight",
    threshold: 15,
    icon: "scale-balance",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "scale-balance",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_3",
    name: "Vigilante",
    description: "Registre seu peso 30 vezes",
    category: "weight",
    threshold: 30,
    icon: "clipboard-text",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 175,
    fitPointsIcon: "clipboard-text",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_4",
    name: "Meticuloso",
    description: "Registre seu peso 60 vezes",
    category: "weight",
    threshold: 60,
    icon: "clipboard-check",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 300,
    fitPointsIcon: "clipboard-check",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_5",
    name: "Cientista Corporal",
    description: "Registre seu peso 100 vezes",
    category: "weight",
    threshold: 100,
    icon: "microscope",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 500,
    fitPointsIcon: "microscope",
    trackedValue: "weightEntryCount",
  },
  {
    id: "hidden_achievement",
    name: "Segredo Revelado",
    description: "Você encontrou um segredo!",
    category: "social",
    hidden: true,
    threshold: 1,
    icon: "lock-open-variant",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "lock-open-variant",
    trackedValue: "secretsFound",
  },
  {
    id: "first_food",
    name: "Primeiro Passo Nutricional",
    description:
      "Você registrou seu primeiro alimento. Continue acompanhando sua nutrição!",
    category: "nutrition",
    threshold: 1,
    icon: "food",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 25,
    fitPointsIcon: "food",
    trackedValue: "firstFoodAdded",
  },
  {
    id: "meal_type_creation",
    name: "Organizador de Refeições",
    description:
      "Você configurou seus tipos de refeições. Organização é o primeiro passo para o sucesso!",
    category: "nutrition",
    threshold: 1,
    icon: "silverware-variant",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 25,
    fitPointsIcon: "silverware-variant",
    trackedValue: "mealTypesCreated",
  },
  {
    id: "workout_type_creation",
    name: "Arquiteto de Treinos",
    description:
      "Você configurou seus tipos de treinos. Comece a construir seu corpo ideal!",
    category: "workout",
    threshold: 1,
    icon: "hammer",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 25,
    fitPointsIcon: "hammer",
    trackedValue: "workoutTypesCreated",
  },
  {
    id: "daily_login_streak_1",
    name: "Primeiros Passos",
    description: "3 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 3,
    icon: "calendar-check",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "calendar-check",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_2",
    name: "Compromisso",
    description: "7 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 7,
    icon: "calendar-month",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "calendar-month",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_3",
    name: "Disciplina",
    description: "14 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 14,
    icon: "calendar-week",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 125,
    fitPointsIcon: "calendar-week",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_4",
    name: "Rotina Sólida",
    description: "30 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 30,
    icon: "calendar-clock",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 250,
    fitPointsIcon: "calendar-clock",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_5",
    name: "Hábito Incorporado",
    description: "60 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 60,
    icon: "calendar-star",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 500,
    fitPointsIcon: "calendar-star",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "early_bird",
    name: "Pássaro Madrugador",
    description:
      "Você treinou antes das 7h da manhã! A disciplina faz parte do seu DNA.",
    category: "workout",
    hidden: true,
    threshold: 1,
    icon: "weather-sunset-up",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "weather-sunset-up",
    trackedValue: "earlyMorningWorkout",
  },
  {
    id: "night_owl",
    name: "Coruja da Noite",
    description:
      "Você treinou depois das 22h! Sua determinação não tem hora para acabar.",
    category: "workout",
    hidden: true,
    threshold: 1,
    icon: "weather-night",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "weather-night",
    trackedValue: "lateNightWorkout",
  },
];

// Função para obter uma conquista pelo ID
export const getAchievementById = (id: string): Achievement | undefined => {
  return ACHIEVEMENTS.find((achievement) => achievement.id === id);
};

// Função para obter conquistas por categoria
export const getAchievementsByCategory = (
  category: AchievementCategory
): Achievement[] => {
  return ACHIEVEMENTS.filter(
    (achievement) => achievement.category === category
  );
};

// Verifica se uma conquista está desbloqueada com base no valor atual
export const isAchievementUnlocked = (
  achievement: Achievement,
  value: number
): boolean => {
  return value >= achievement.threshold;
};
