import { MaterialCommunityIcons } from "@expo/vector-icons";

export type AchievementCategory =
  | "workout"
  | "nutrition"
  | "consistency"
  | "social"
  | "weight"
  | "water"
  | "account";

export type AchievementRarity =
  | "common"
  | "uncommon"
  | "rare"
  | "epic"
  | "legendary";

export interface Achievement {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  hidden?: boolean; // Se a conquista é secreta
  threshold: number; // Valor necessário para desbloquear
  icon: keyof typeof MaterialCommunityIcons.glyphMap;
  rarity: AchievementRarity;
  badgeColor: string;
  fitPoints: number;
  fitPointsIcon: keyof typeof MaterialCommunityIcons.glyphMap;
  trackedValue: string; // Nome da propriedade que será rastreada (ex: "workoutCount", "loginDays")
}

// Cores para as medalhas baseadas na raridade
export const RARITY_COLORS = {
  common: "#BDBDBD", // Cinza (ligeiramente menos opaco)
  uncommon: "#2ECC71", // Verde Esmeralda
  rare: "#007BFF", // Azul Vibrante (Bootstrap Primary)
  epic: "#8E44AD", // Roxo Wisteria (Mais Vibrante)
  legendary: "#FFD700", // Dourado (consistente com Fit Level)
};

// Banco de dados de conquistas
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "workout_completion_1",
    name: "Primeiros Passos",
    description: "Complete seu primeiro treino",
    category: "workout",
    threshold: 1,
    icon: "weight-lifter",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 20,
    fitPointsIcon: "weight-lifter",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_2",
    name: "Dedicado",
    description: "Complete 5 treinos",
    category: "workout",
    threshold: 5,
    icon: "dumbbell",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "dumbbell",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_3",
    name: "Consistente",
    description: "Complete 25 treinos",
    category: "workout",
    threshold: 25,
    icon: "arm-flex-outline",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "arm-flex-outline",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_4",
    name: "Atleta",
    description: "Complete 100 treinos",
    category: "workout",
    threshold: 100,
    icon: "trophy-outline",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 340,
    fitPointsIcon: "trophy-outline",
    trackedValue: "workoutCount",
  },
  {
    id: "workout_completion_5",
    name: "Lendário",
    description: "Complete 365 treinos",
    category: "workout",
    threshold: 365,
    icon: "trophy",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "trophy",
    trackedValue: "workoutCount",
  },
  {
    id: "streak_days_1",
    name: "Faísca",
    description: "3 dias consecutivos de treino",
    category: "consistency",
    threshold: 3,
    icon: "fire",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 75,
    fitPointsIcon: "fire",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_2",
    name: "Chama",
    description: "7 dias consecutivos de treino",
    category: "consistency",
    threshold: 7,
    icon: "torch",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "torch",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_3",
    name: "Incêndio",
    description: "14 dias consecutivos de treino",
    category: "consistency",
    threshold: 14,
    icon: "fireplace",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "fireplace",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_4",
    name: "Inferno",
    description: "30 dias consecutivos de treino",
    category: "consistency",
    threshold: 30,
    icon: "fire-circle",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 540,
    fitPointsIcon: "fire-circle",
    trackedValue: "streakDays",
  },
  {
    id: "streak_days_5",
    name: "Fênix",
    description: "90 dias consecutivos de treino",
    category: "consistency",
    threshold: 90,
    icon: "meteor",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "meteor",
    trackedValue: "streakDays",
  },
  {
    id: "nutrition_goals_1",
    name: "Iniciante Nutricional",
    description: "Atinja suas metas de macros 1 dia",
    category: "nutrition",
    threshold: 1,
    icon: "food-apple",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 20,
    fitPointsIcon: "food-apple",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_2",
    name: "Consciente",
    description: "Atinja suas metas de macros 7 dias",
    category: "nutrition",
    threshold: 7,
    icon: "food-apple-outline",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "food-apple-outline",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_3",
    name: "Disciplinado",
    description: "Atinja suas metas de macros 30 dias",
    category: "nutrition",
    threshold: 30,
    icon: "fruit-watermelon",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "fruit-watermelon",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_4",
    name: "Nutricionista Amador",
    description: "Atinja suas metas de macros 90 dias",
    category: "nutrition",
    threshold: 90,
    icon: "food-variant",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 550,
    fitPointsIcon: "food-variant",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "nutrition_goals_5",
    name: "Guru Nutricional",
    description: "Atinja suas metas de macros 180 dias",
    category: "nutrition",
    threshold: 180,
    icon: "food-fork-drink",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 900,
    fitPointsIcon: "food-fork-drink",
    trackedValue: "nutritionGoalDays",
  },
  {
    id: "water_intake_1",
    name: "Gota d'água",
    description: "Atinja sua meta de água 1 dia",
    category: "water",
    threshold: 1,
    icon: "water-outline",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 20,
    fitPointsIcon: "water-outline",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_2",
    name: "Fonte",
    description: "Atinja sua meta de água 7 dias",
    category: "water",
    threshold: 7,
    icon: "water",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "water",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_3",
    name: "Rio",
    description: "Atinja sua meta de água 30 dias",
    category: "water",
    threshold: 30,
    icon: "cup-water",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "cup-water",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_4",
    name: "Cascata",
    description: "Atinja sua meta de água 90 dias",
    category: "water",
    threshold: 90,
    icon: "waves",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 400,
    fitPointsIcon: "waves",
    trackedValue: "waterGoalDays",
  },
  {
    id: "water_intake_5",
    name: "Oceano",
    description: "Atinja sua meta de água 180 dias",
    category: "water",
    threshold: 180,
    icon: "diving-helmet",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 750,
    fitPointsIcon: "diving-helmet",
    trackedValue: "waterGoalDays",
  },
  {
    id: "weight_goals_1",
    name: "Primeiros Quilos",
    description: "Alcance 10% do seu objetivo de peso",
    category: "weight",
    threshold: 10,
    icon: "scale-bathroom",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "scale-bathroom",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_2",
    name: "No Caminho",
    description: "Alcance 25% do seu objetivo de peso",
    category: "weight",
    threshold: 25,
    icon: "progress-check",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 150,
    fitPointsIcon: "progress-check",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_3",
    name: "Meio Caminho",
    description: "Alcance 50% do seu objetivo de peso",
    category: "weight",
    threshold: 50,
    icon: "progress-clock",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "progress-clock",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_4",
    name: "Quase Lá",
    description: "Alcance 75% do seu objetivo de peso",
    category: "weight",
    threshold: 75,
    icon: "progress-star",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 410,
    fitPointsIcon: "progress-star",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "weight_goals_5",
    name: "Metamorfose Completa",
    description: "Alcance 100% do seu objetivo de peso",
    category: "weight",
    threshold: 100,
    icon: "butterfly",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 500,
    fitPointsIcon: "butterfly",
    trackedValue: "weightGoalPercentage",
  },
  {
    id: "exercise_variety_1",
    name: "Curioso",
    description: "Experimente 5 exercícios diferentes",
    category: "workout",
    threshold: 5,
    icon: "lightbulb-on-outline",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "lightbulb-on-outline",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_2",
    name: "Aventureiro",
    description: "Experimente 15 exercícios diferentes",
    category: "workout",
    threshold: 15,
    icon: "yoga",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "yoga",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_3",
    name: "Versátil",
    description: "Experimente 30 exercícios diferentes",
    category: "workout",
    threshold: 30,
    icon: "run",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 175,
    fitPointsIcon: "run",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_4",
    name: "Mestre da Variedade",
    description: "Experimente 50 exercícios diferentes",
    category: "workout",
    threshold: 50,
    icon: "karate",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 340,
    fitPointsIcon: "karate",
    trackedValue: "uniqueExercises",
  },
  {
    id: "exercise_variety_5",
    name: "Enciclopédia Viva",
    description: "Experimente 100 exercícios diferentes",
    category: "workout",
    threshold: 100,
    icon: "book-open-variant",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 600,
    fitPointsIcon: "book-open-variant",
    trackedValue: "uniqueExercises",
  },
  {
    id: "app_usage_1",
    name: "Novato",
    description: "Use o app por 7 dias",
    category: "consistency",
    threshold: 7,
    icon: "cellphone-check",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "cellphone-check",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_2",
    name: "Regular",
    description: "Use o app por 30 dias",
    category: "consistency",
    threshold: 30,
    icon: "cellphone-arrow-down",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "cellphone-arrow-down",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_3",
    name: "Lealdade Trimestral",
    description: "Use o app por 90 dias",
    category: "consistency",
    threshold: 90,
    icon: "cellphone-link",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "cellphone-link",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_4",
    name: "Leal",
    description: "Use o app por 180 dias",
    category: "consistency",
    threshold: 180,
    icon: "cellphone-message",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 540,
    fitPointsIcon: "cellphone-message",
    trackedValue: "appUsageDays",
  },
  {
    id: "app_usage_5",
    name: "Vitalício",
    description: "Use o app por 365 dias",
    category: "consistency",
    threshold: 365,
    icon: "cellphone-nfc",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "cellphone-nfc",
    trackedValue: "appUsageDays",
  },
  {
    id: "meal_tracking_1",
    name: "Iniciante Culinário",
    description: "Registre 7 dias de refeições",
    category: "nutrition",
    threshold: 7,
    icon: "silverware-fork-knife",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "silverware-fork-knife",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_2",
    name: "Gourmet Amador",
    description: "Registre 30 dias de refeições",
    category: "nutrition",
    threshold: 30,
    icon: "silverware",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "silverware",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_3",
    name: "Chef de Nutrição",
    description: "Registre 90 dias de refeições",
    category: "nutrition",
    threshold: 90,
    icon: "food-steak",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "food-steak",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_4",
    name: "Mestre Culinário",
    description: "Registre 180 dias de refeições",
    category: "nutrition",
    threshold: 180,
    icon: "food-turkey",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 540,
    fitPointsIcon: "food-turkey",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "meal_tracking_5",
    name: "Lenda da Gastronomia",
    description: "Registre 365 dias de refeições",
    category: "nutrition",
    threshold: 365,
    icon: "chef-hat",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "chef-hat",
    trackedValue: "mealTrackingDays",
  },
  {
    id: "weight_tracking_1",
    name: "Primeiro Registro",
    description: "Registre seu peso 1 vez",
    category: "weight",
    threshold: 2,
    icon: "scale",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 35,
    fitPointsIcon: "scale",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_2",
    name: "Atento",
    description: "Registre seu peso 10 vezes",
    category: "weight",
    threshold: 10,
    icon: "scale-balance",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 100,
    fitPointsIcon: "scale-balance",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_3",
    name: "Vigilante",
    description: "Registre seu peso 25 vezes",
    category: "weight",
    threshold: 20,
    icon: "clipboard-text",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 175,
    fitPointsIcon: "clipboard-text",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_4",
    name: "Meticuloso",
    description: "Registre seu peso 50 vezes",
    category: "weight",
    threshold: 40,
    icon: "clipboard-check",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 340,
    fitPointsIcon: "clipboard-check",
    trackedValue: "weightEntryCount",
  },
  {
    id: "weight_tracking_5",
    name: "Cientista Corporal",
    description: "Registre seu peso 100 vezes",
    category: "weight",
    threshold: 100,
    icon: "microscope",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 600,
    fitPointsIcon: "microscope",
    trackedValue: "weightEntryCount",
  },
  {
    id: "hidden_achievement",
    name: "Segredo Revelado",
    description: "Você encontrou um segredo!",
    category: "social",
    hidden: true,
    threshold: 1,
    icon: "lock-open-variant",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "lock-open-variant",
    trackedValue: "secretsFound",
  },
  {
    id: "first_food",
    name: "Primeiro Passo Nutricional",
    description:
      "Você registrou seu primeiro alimento. Continue acompanhando sua nutrição!",
    category: "nutrition",
    threshold: 1,
    icon: "food",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 15,
    fitPointsIcon: "food",
    trackedValue: "firstFoodAdded",
  },
  {
    id: "meal_type_creation",
    name: "Organizador de Refeições",
    description:
      "Você configurou seus tipos de refeições. Organização é o primeiro passo para o sucesso!",
    category: "nutrition",
    threshold: 1,
    icon: "silverware-variant",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 15,
    fitPointsIcon: "silverware-variant",
    trackedValue: "mealTypesCreated",
  },
  {
    id: "workout_type_creation",
    name: "Arquiteto de Treinos",
    description:
      "Você configurou seus tipos de treinos. Comece a construir seu corpo ideal!",
    category: "workout",
    threshold: 1,
    icon: "hammer",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 40,
    fitPointsIcon: "hammer",
    trackedValue: "workoutTypesCreated",
  },
  {
    id: "daily_login_streak_1",
    name: "Check-in Triplo",
    description: "3 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 3,
    icon: "calendar-check",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 50,
    fitPointsIcon: "calendar-check",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_2",
    name: "Compromisso",
    description: "7 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 7,
    icon: "calendar-month",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "calendar-month",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_3",
    name: "Presença Constante",
    description: "14 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 14,
    icon: "calendar-week",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 125,
    fitPointsIcon: "calendar-week",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_4",
    name: "Rotina Sólida",
    description: "30 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 30,
    icon: "calendar-clock",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 280,
    fitPointsIcon: "calendar-clock",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "daily_login_streak_5",
    name: "Hábito Incorporado",
    description: "60 dias consecutivos de uso do aplicativo",
    category: "consistency",
    threshold: 60,
    icon: "calendar-star",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 600,
    fitPointsIcon: "calendar-star",
    trackedValue: "dailyLoginStreak",
  },
  {
    id: "early_bird",
    name: "Pássaro Madrugador",
    description:
      "Você treinou antes das 7h da manhã! A disciplina faz parte do seu DNA.",
    category: "workout",
    hidden: true,
    threshold: 1,
    icon: "weather-sunset-up",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "weather-sunset-up",
    trackedValue: "earlyMorningWorkout",
  },
  {
    id: "night_owl",
    name: "Coruja da Noite",
    description:
      "Você treinou depois das 22h! Sua determinação não tem hora para acabar.",
    category: "workout",
    hidden: true,
    threshold: 1,
    icon: "weather-night",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "weather-night",
    trackedValue: "lateNightWorkout",
  },
  {
    id: "caloric_goal_1",
    name: "Nutrição Precisa",
    description: "Atinja sua meta calórica diária pela primeira vez",
    category: "nutrition",
    threshold: 1,
    icon: "target",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 30,
    fitPointsIcon: "target",
    trackedValue: "caloricGoalDays",
  },
  {
    id: "caloric_goal_2",
    name: "Contador de Calorias",
    description: "Atinja sua meta calórica diária por 7 dias",
    category: "nutrition",
    threshold: 7,
    icon: "chart-bar",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "chart-bar",
    trackedValue: "caloricGoalDays",
  },
  {
    id: "caloric_goal_3",
    name: "Mestre das Calorias",
    description: "Atinja sua meta calórica diária por 30 dias",
    category: "nutrition",
    threshold: 30,
    icon: "calculator-variant",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "calculator-variant",
    trackedValue: "caloricGoalDays",
  },
  {
    id: "caloric_goal_4",
    name: "Perito Calórico",
    description: "Atinja sua meta calórica diária por 90 dias",
    category: "nutrition",
    threshold: 90,
    icon: "chart-line",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 540,
    fitPointsIcon: "chart-line",
    trackedValue: "caloricGoalDays",
  },
  {
    id: "caloric_goal_5",
    name: "Precisão Nutricional Lendária",
    description: "Atinja sua meta calórica diária por 180 dias",
    category: "nutrition",
    threshold: 180,
    icon: "chart-gantt",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "chart-gantt",
    trackedValue: "caloricGoalDays",
  },
  {
    id: "daily_steps_1",
    name: "Em Movimento",
    description: "Alcance 2.500 passos em um dia",
    category: "consistency",
    threshold: 2500,
    icon: "shoe-print",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 20,
    fitPointsIcon: "shoe-print",
    trackedValue: "dailySteps",
  },
  {
    id: "daily_steps_2",
    name: "Caminhante",
    description: "Alcance 5.000 passos em um dia",
    category: "consistency",
    threshold: 5000,
    icon: "walk",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 50,
    fitPointsIcon: "walk",
    trackedValue: "dailySteps",
  },
  {
    id: "daily_steps_3",
    name: "Maratonista Urbano",
    description: "Alcance 10.000 passos em um dia",
    category: "consistency",
    threshold: 10000,
    icon: "run-fast",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 80,
    fitPointsIcon: "run-fast",
    trackedValue: "dailySteps",
  },
  {
    id: "daily_steps_4",
    name: "Explorador Incansável",
    description: "Alcance 15.000 passos em um dia",
    category: "consistency",
    threshold: 15000,
    icon: "hiking",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 180,
    fitPointsIcon: "hiking",
    trackedValue: "dailySteps",
  },
  {
    id: "daily_steps_5",
    name: "Nômade Incansável",
    description: "Alcance 20.000 passos em um dia",
    category: "consistency",
    threshold: 20000,
    icon: "map-marker-distance",
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 300,
    fitPointsIcon: "map-marker-distance",
    trackedValue: "dailySteps",
  },
  {
    id: "hidden_24h_warrior",
    name: "Guerreiro 24h",
    description: "Treinou tanto de madrugada quanto tarde da noite.",
    category: "workout",
    hidden: true,
    threshold: 1,
    icon: "clock-time-twelve-outline",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 230,
    fitPointsIcon: "clock-time-twelve-outline",
    trackedValue: "hasEarlyBirdAndNightOwl",
  },
  {
    id: "hidden_perfect_week",
    name: "Semana Perfeita",
    description: "Registrou treinos em todos os 7 dias de uma semana.",
    category: "consistency",
    hidden: true,
    threshold: 1,
    icon: "calendar-check-outline",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 280,
    fitPointsIcon: "calendar-check-outline",
    trackedValue: "perfectWeeks",
  },
  {
    id: "hidden_consistent_chef",
    name: "Chef Consistente",
    description: "Registrou refeições por 30 dias consecutivos.",
    category: "nutrition",
    hidden: true,
    threshold: 30,
    icon: "silverware-clean", // Ícone diferente para evitar repetição com meal_tracking_5
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 180,
    fitPointsIcon: "silverware-clean",
    trackedValue: "consecutiveMealDays",
  },
  {
    id: "hidden_macro_master",
    name: "Mestre dos Macros",
    description:
      "Atingiu as metas diárias exatas de Calorias, Proteína, Carboidratos e Gordura no mesmo dia.",
    category: "nutrition",
    hidden: true,
    threshold: 1, // Desbloqueia na primeira vez que acontece
    icon: "scale-balance", // Ícone diferente de weight_tracking_2
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 280,
    fitPointsIcon: "scale-balance",
    trackedValue: "exactMacroDays",
  },
  {
    id: "hidden_weight_vigilant",
    name: "Vigilante do Peso",
    description: "Registrou o peso corporal por 7 dias consecutivos.",
    category: "weight",
    hidden: true,
    threshold: 7,
    icon: "calendar-sync",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 120,
    fitPointsIcon: "calendar-sync",
    trackedValue: "consecutiveWeightDays",
  },
  {
    id: "protein_goal_1",
    name: "Iniciante da Proteína",
    description: "Atinja sua meta diária de proteína pela primeira vez",
    category: "nutrition",
    threshold: 1,
    icon: "food-drumstick-outline",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 30,
    fitPointsIcon: "food-drumstick-outline",
    trackedValue: "proteinGoalDays",
  },
  {
    id: "protein_goal_2",
    name: "Discípulo da Proteína",
    description: "Atinja sua meta diária de proteína por 7 dias",
    category: "nutrition",
    threshold: 7,
    icon: "food-drumstick",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 125,
    fitPointsIcon: "food-drumstick",
    trackedValue: "proteinGoalDays",
  },
  {
    id: "protein_goal_3",
    name: "Adepto da Proteína",
    description: "Atinja sua meta diária de proteína por 30 dias",
    category: "nutrition",
    threshold: 30,
    icon: "food-steak", // Reutilizando, mas ok
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 250,
    fitPointsIcon: "food-steak",
    trackedValue: "proteinGoalDays",
  },
  {
    id: "protein_goal_4",
    name: "Mestre da Proteína",
    description: "Atinja sua meta diária de proteína por 60 dias",
    category: "nutrition",
    threshold: 60,
    icon: "food-turkey", // Reutilizando, mas ok
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 540,
    fitPointsIcon: "food-turkey",
    trackedValue: "proteinGoalDays",
  },
  {
    id: "protein_goal_5",
    name: "Lenda da Proteína",
    description: "Atinja sua meta diária de proteína por 100 dias",
    category: "nutrition",
    threshold: 100,
    icon: "cow", // Ícone representativo
    rarity: "legendary",
    badgeColor: RARITY_COLORS.legendary,
    fitPoints: 1000,
    fitPointsIcon: "cow",
    trackedValue: "proteinGoalDays",
  },
  // Novas conquistas para aplicação de progressão
  {
    id: "progression_apply_1",
    name: "Evolução Iniciada",
    description: "Aplique sua primeira sugestão de progressão de treino",
    category: "workout", // Ou talvez "consistency"?
    threshold: 1,
    icon: "trending-up",
    rarity: "common",
    badgeColor: RARITY_COLORS.common,
    fitPoints: 30,
    fitPointsIcon: "trending-up",
    trackedValue: "appliedProgressionCount",
  },
  {
    id: "progression_apply_2",
    name: "Sempre Melhorando",
    description: "Aplique 10 sugestões de progressão",
    category: "workout",
    threshold: 10,
    icon: "chart-line-variant",
    rarity: "uncommon",
    badgeColor: RARITY_COLORS.uncommon,
    fitPoints: 75,
    fitPointsIcon: "chart-line-variant",
    trackedValue: "appliedProgressionCount",
  },
  {
    id: "progression_apply_3",
    name: "Mestre da Progressão",
    description: "Aplique 50 sugestões de progressão",
    category: "workout",
    threshold: 50,
    icon: "school",
    rarity: "rare",
    badgeColor: RARITY_COLORS.rare,
    fitPoints: 150,
    fitPointsIcon: "school",
    trackedValue: "appliedProgressionCount",
  },
  {
    id: "progression_apply_4",
    name: "Lenda da Evolução",
    description: "Aplique 100 sugestões de progressão",
    category: "workout",
    threshold: 100,
    icon: "trophy-award",
    rarity: "epic",
    badgeColor: RARITY_COLORS.epic,
    fitPoints: 300,
    fitPointsIcon: "trophy-award",
    trackedValue: "appliedProgressionCount",
  },
];

// Função para obter uma conquista pelo ID
export const getAchievementById = (id: string): Achievement | undefined => {
  return ACHIEVEMENTS.find((achievement) => achievement.id === id);
};

// Função para obter conquistas por categoria
export const getAchievementsByCategory = (
  category: AchievementCategory
): Achievement[] => {
  return ACHIEVEMENTS.filter(
    (achievement) => achievement.category === category
  );
};

// Verifica se uma conquista está desbloqueada com base no valor atual
export const isAchievementUnlocked = (
  achievement: Achievement,
  value: number
): boolean => {
  return value >= achievement.threshold;
};
