// Chaves para armazenamento no AsyncStorage
export const KEYS = {
  NUTRITION_DATA: "pumpgym_nutrition_data",
  PENDING_OPERATIONS: "pumpgym_pending_operations",
  ONBOARDING_COMPLETED: "pumpgym_onboarding_completed",
  USER_DATA: "pumpgym_user_data",
  ONBOARDING_DATA: "pumpgym_onboarding_data",
  ONBOARDING_STEP: "pumpgym_onboarding_step",
  PENDING_SYNC: "pumpgym_pending_sync",
  TEMP_NUTRITION_DATA: "@temp_nutrition_data",
  MEALS_KEY: "@meals:",
  MEAL_TYPES: "pumpgym_meal_types",
  SEARCH_HISTORY: "pumpgym_search_history",
  WORKOUTS: "pumpgym_workouts",
  WORKOUT_TYPES: "pumpgym_workout_types",
  AVAILABLE_WORKOUT_TYPES: "pumpgym_available_workout_types",
  TRAINING_GOALS: "pumpgym_training_goals",
  WATER_INTAKE: "pumpgym_water_intake",
  STEPS_COUNT: "pumpgym_steps_count",
  LAST_PROGRESSION_APPLIED_CHECK_DATE: "pumpgym_last_progression_check_date",
};
